MVC .NET/MVCPracticalTest/MVCPracticalTest/MVCPracticalTest/Models/Contacts.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVCPracticalTest.Models
{
    [Table("Contacts")]
    public class Contacts
    {
        public int Id { get; set; }

        [StringLength(100),Required]
       
        public string Name { get; set; }

        [StringLength(100),Required]
        public string Number { get; set; }

        [StringLength(100),Required]
        public string GroupName { get; set; }

        public DateTime HireDate { get; set; }

        public DateTime BirthDay { get; set; }

    }
}

MVC .NET/MVCPracticalTest/MVCPracticalTest/MVCPracticalTest/Controllers/ContactController.cs
using MVCPracticalTest.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MVCPracticalTest.Controllers
{
    public class ContactController : Controller
    {
        ApplicationDbContext context;

        public ContactController()
        {
            context = new ApplicationDbContext();
        }
        // GET: Contact
        public ActionResult Index()
        {
            return View(context.Contacts.ToList());
        }

        public ActionResult Create()
        {
            return View(new Contacts());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async  Task<ActionResult> Create(Contacts model)
        {
            if (ModelState.IsValid)
            {
                context.Contacts.Add(model);
                await context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(model);
        }

    }
}

MVC .NET/MVCPracticalTest/MVCPracticalTest/MVCPracticalTest/Views/Contact/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>
<div>
    @using (Html.BeginForm("Create", "Contact", FormMethod.Post))
    {
        @Html.TextBoxFor(m => m.Name, new { @placeholder = "Contact Name" })
        @Html.TextBoxFor(m => m.Number, new { @placeholder = "Contact Number" })
        @Html.TextBoxFor(m => m.GroupName, new { @placeholder = "Group Name" })
        @Html.TextBoxFor(m => m.HireDate, new { @placeholder = "HireDate" })
        @Html.TextBoxFor(m => m.BirthDay, new { @placeholder = "BirthDay" })
    }
    <form action="#" method="post">
        <input type="text" name="Contact Name" placeholder="Contact Name" />
        <input type="text" name="Contact Number" placeholder="Contact Number" />
        <input type="text" name="Group Name" placeholder="Group Name" />
        <input type="datetime" name="Hire Date" placeholder="Hire Date" />
        <input type="datetime" name="Birthday" placeholder="Birthday" />

    </form>
</div>

MVC .NET/MVCPracticalTest/MVCPracticalTest/MVCPracticalTest/Views/Contact/Index.cshtml
@model IEnumerable<MVCPracticalTest.Models.Contacts>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Number)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GroupName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HireDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BirthDay)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Number)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GroupName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HireDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BirthDay)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>